#!/usr/bin/env python3
"""Compare the authoritative data against the SWAT+ source-derived schema.

The artifacts under ``schemas/`` are generated by ``swatplus-doc-builder`` from
a pinned SWAT+ release.  For each input database file they record the fields
SWAT+ actually *reads* -- name, Fortran type, units -- in order.  This script
compares three things that must stay in agreement:

    schemas/swatplus-<ver>.json   what SWAT+ reads       (the model)
    scripts/swat_config.py        what we expect         (FILE_SCHEMAS)
    database_files/*              what we ship           (the data)

Why the three can legitimately differ
-------------------------------------
Our schemas count the columns in a file's **header row**.  The artifact counts
the fields SWAT+ **consumes**.  Those are not the same number: SWAT+ reads each
record with list-directed I/O over a whole derived type, so trailing columns
beyond the last component -- typically a free-text ``description`` -- are never
consumed and are simply ignored.  14 of our files are in exactly this state and
they are correct as they stand.

The differences that matter are the other two shapes:

``underfilled``
    The file supplies FEWER columns than SWAT+ reads.  List-directed input does
    not stop at the end of a line: it keeps consuming to satisfy the remaining
    variables, so SWAT+ reads the next record's tokens into the current one --
    a type error, or silently shifted values.  This is a defect in the data.

``type_mismatch``
    Arity agrees but we require a numeric value where SWAT+ declares a
    character field (or vice versa).

A limitation worth stating plainly
----------------------------------
An extra column *inserted mid-row* -- which shifts every later value into the
wrong variable, silently and with plausible numbers -- is the most dangerous
shape of all, and it cannot be detected automatically here.  Column names in
the text files do not match the Fortran component names by any reliable rule
(``falltmp``/``fall_tmp`` but also ``timp``/``tmp_lag``, ``covmx``/
``snow_h2o``), so a positional name comparison produces too many false
alarms to be useful.  Such findings come from human inspection and are
recorded as ``review_notes`` in ``metadata/schema_drift_waivers.json`` so they
are surfaced on every run rather than living only in someone's memory.

Known, accepted drift is recorded as ``waivers`` in the same file with a
reason, so it stays visible in every report instead of being silently
tolerated -- and so CI can stay green while a data fix is pending.

Usage:
    python scripts/schema_sync.py [--repo-root .] [--schema-version 62.0.0]
                                  [--strict]

``--strict`` fails on waived drift too (use when verifying a waiver is still
needed).
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from swat_common import parse_name_keyed_table  # noqa: E402
from swat_config import (  # noqa: E402
    DATABASE_FILES_DIR,
    EXPECTED_BY_NAME,
    FILE_SCHEMAS,
    METADATA_DIR,
    NAME_KEYED_FORMATS,
)

SCHEMAS_DIR = "schemas"
WAIVERS_FILE = "schema_drift_waivers.json"

# Trailing columns SWAT+ never reads.  Present in the header for human
# readability only; a file may carry these beyond the last read field.
UNREAD_TRAILING = ("description", "descrip", "desc", "treat", "cond_cov")

# Drift classifications, worst first.
UNDERFILLED = "underfilled"      # data provides fewer fields than SWAT+ reads
MIDROW_EXTRA = "midrow_extra"    # extra column shifts subsequent values
TYPE_MISMATCH = "type_mismatch"  # we treat a field as numeric, SWAT+ does not
TRAILING_UNREAD = "trailing_unread"  # benign: extra trailing text columns
MATCH = "match"

BLOCKING = {UNDERFILLED, MIDROW_EXTRA, TYPE_MISMATCH}


@dataclass
class Finding:
    file: str
    kind: str
    detail: str
    waived: bool = False
    waiver_reason: str = ""


@dataclass
class Report:
    schema_version: str
    findings: list[Finding] = field(default_factory=list)
    unresolved: list[dict] = field(default_factory=list)
    not_in_artifact: list[str] = field(default_factory=list)
    review_notes: list[dict] = field(default_factory=list)

    @property
    def blocking(self) -> list[Finding]:
        return [f for f in self.findings
                if f.kind in BLOCKING and not f.waived]

    @property
    def waived(self) -> list[Finding]:
        return [f for f in self.findings if f.waived]


def load_artifact(repo_root: Path, version: str | None) -> tuple[dict, str]:
    d = repo_root / SCHEMAS_DIR
    if not d.is_dir():
        raise SystemExit(f"no {SCHEMAS_DIR}/ directory; nothing to compare")
    if version:
        path = d / f"swatplus-{version}.json"
    else:
        candidates = sorted(d.glob("swatplus-*.json"))
        if not candidates:
            raise SystemExit(f"no schema artifacts in {d}")
        path = candidates[-1]
    if not path.is_file():
        raise SystemExit(f"schema artifact not found: {path}")
    return json.loads(path.read_text(encoding="utf-8")), path.name


def load_waivers(repo_root: Path) -> tuple[dict[str, dict], list[dict]]:
    """Return (accepted-drift waivers by file, manual review notes)."""
    p = repo_root / METADATA_DIR / WAIVERS_FILE
    if not p.is_file():
        return {}, []
    doc = json.loads(p.read_text(encoding="utf-8"))
    return ({w["file"]: w for w in doc.get("waivers", [])},
            doc.get("review_notes", []))


def analyze(repo_root: str | Path, version: str | None = None) -> Report:
    repo_root = Path(repo_root)
    artifact, artifact_name = load_artifact(repo_root, version)
    waivers, review_notes = load_waivers(repo_root)
    files = artifact.get("files", {})

    report = Report(schema_version=artifact.get("swatplus_version", "unknown"))
    report.unresolved = artifact.get("unresolved", [])
    report.review_notes = review_notes

    for name, schema in sorted(FILE_SCHEMAS.items()):
        spec = EXPECTED_BY_NAME.get(name)
        if not spec or spec["fmt"] not in NAME_KEYED_FORMATS:
            continue
        entry = files.get(name)
        if entry is None:
            report.not_in_artifact.append(name)
            continue

        read_fields = entry["fields"]
        header = schema["columns"]
        finding = _classify(name, header, schema, read_fields)
        if finding.kind != MATCH:
            w = waivers.get(name)
            if w and w.get("kind") == finding.kind:
                finding.waived = True
                finding.waiver_reason = w.get("reason", "")
            report.findings.append(finding)

    return report


def _classify(name: str, header: list[str], schema: dict,
              read_fields: list[dict]) -> Finding:
    n_read = len(read_fields)
    n_head = len(header)

    if n_head < n_read:
        # Name the source fields in the region the file runs out in.  Reporting
        # only read_fields[n_head:] would be misleading: the file's own last
        # column sits at the position where SWAT+ expects the first unsatisfied
        # field, so that position is where the read actually goes wrong.
        tail = read_fields[max(0, n_head - 1):]
        expect = ", ".join(f"{f['fortran_name']} ({f['fortran_type']})"
                           for f in tail)
        ours_last = header[-1] if header else "?"
        return Finding(
            name, UNDERFILLED,
            f"SWAT+ reads {n_read} fields, the file supplies {n_head}. From "
            f"position {max(0, n_head - 1)} SWAT+ expects: {expect}; the file "
            f"has {ours_last!r} there and then ends. List-directed input does "
            f"not stop at end-of-line, so it will consume the next record's "
            f"tokens to finish the read.")

    if n_head > n_read:
        # Columns at or beyond position n_read are never consumed: SWAT+
        # satisfies its variable list and abandons the rest of the record.
        # This holds whatever those columns are called, so classification is
        # by position, not by name.
        extra = header[n_read:]
        return Finding(
            name, TRAILING_UNREAD,
            f"{n_head - n_read} column(s) {extra} sit beyond the {n_read} "
            f"fields SWAT+ reads and are never consumed; harmless.")

    # Same arity: check that our numeric expectations match the Fortran types.
    src_numeric = {f["position"] for f in read_fields if f["numeric"]}
    ours_numeric = set(schema["numeric"])
    over = sorted(ours_numeric - src_numeric)
    if over:
        cols = [header[i] for i in over if i < len(header)]
        return Finding(
            name, TYPE_MISMATCH,
            f"we require numeric values in column(s) {cols} but SWAT+ declares "
            f"them non-numeric")
    return Finding(name, MATCH, "")


def render(report: Report, strict: bool) -> int:
    print(f"Schema sync against SWAT+ {report.schema_version}\n")

    by_kind: dict[str, list[Finding]] = {}
    for f in report.findings:
        by_kind.setdefault(f.kind, []).append(f)

    # A file carrying a manual review note is not reported as harmless, even
    # when positional analysis says its extra columns are trailing -- the note
    # exists precisely because that conclusion is wrong for it.
    noted = {n.get("file") for n in report.review_notes}
    benign = [f for f in by_kind.get(TRAILING_UNREAD, []) if f.file not in noted]
    if benign:
        print(f"OK  {len(benign)} file(s) carry trailing columns SWAT+ never "
              f"reads (expected):")
        for f in benign:
            print(f"      {f.file}: {f.detail}")
        print()

    for kind in (UNDERFILLED, MIDROW_EXTRA, TYPE_MISMATCH):
        items = by_kind.get(kind, [])
        for f in items:
            tag = "WAIVED " if f.waived else "DRIFT  "
            print(f"{tag}[{kind}] {f.file}")
            print(f"        {f.detail}")
            if f.waived:
                print(f"        waiver: {f.waiver_reason}")
        if items:
            print()

    if report.review_notes:
        print("REVIEW  findings from human inspection (not auto-detectable):")
        for n in report.review_notes:
            print(f"        {n.get('file')}: {n.get('note')}")
        print()

    if report.unresolved:
        print("NOTE  the generator could not resolve a reader for:")
        for u in report.unresolved:
            print(f"      {u.get('file')}: {u.get('reason')}")
        print()

    if report.not_in_artifact:
        print("NOTE  no entry in the artifact (validated by header only): "
              f"{report.not_in_artifact}\n")

    blocking = report.blocking
    waived = report.waived
    if strict and waived:
        print(f"FAILED (strict): {len(waived)} waived finding(s) present")
        return 1
    if blocking:
        print(f"FAILED: {len(blocking)} unwaived drift finding(s)")
        return 1
    msg = "OK: no unwaived schema drift"
    if waived:
        msg += f" ({len(waived)} waived, still tracked)"
    print(msg)
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--schema-version", default=None,
                    help="e.g. 62.0.0 (default: highest available)")
    ap.add_argument("--strict", action="store_true",
                    help="also fail on waived drift")
    args = ap.parse_args(argv)
    report = analyze(args.repo_root, args.schema_version)
    return render(report, args.strict)


if __name__ == "__main__":
    raise SystemExit(main())
